
#James Lee (RedID: 820655947)
#James Romanov (RedID: 820821671)


wordcount: wordcount.o
	gcc -o wordcount wordcount.o -lpthread

wordcount.o: wordcount.c
	gcc -c wordcount.c

clean:
	rm -f *.o wordcount
